---
kind: pipeline
name: default
clone:
steps:
  - name: timestamp
    image: joomlaprojects/docker-images:updater
    environment:
      ACCESS_TOKEN:
        from_secret: ACCESS_TOKEN
      KEY_TIMESTAMP:
        from_secret: KEY_TIMESTAMP
      GIT_USER_NAME: Joomla Drone
      GIT_USER_EMAIL: ci@joomla.org
      GIT_BASE_BRANCH_NAME: main
      GIT_TARGET_BRANCH_NAME: ${DRONE_BRANCH}
    commands:
      - mkdir -p /go/keys || true
      - echo $$KEY_TIMESTAMP > /go/keys/timestamp.json
      - cd /go
      - /tuf/docker-entrypoint.sh update-timestamp

  - name: upload
    image: joomlaprojects/docker-images:packager
    environment:
      rclone_key:
        from_secret: RCLONE_KEY
      rclone_user:
        from_secret: RCLONE_USER
      rclone_host:
        from_secret: RCLONE_HOST
      rclone_root:
        from_secret: RCLONE_ROOT
      GITHUB_TOKEN:
        from_secret: ACCESS_TOKEN
    commands:
      - mkdir -p ~/.ssh
      - eval $(ssh-agent -s)
      - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
      - echo "$rclone_key" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ssh-add
      - rclone config create upload sftp host $rclone_host user $rclone_user port 22
      - rclone copy ./repository/ upload:$rclone_root/main
      - /bin/add_github_status.sh "Repository deployed" "Tuf Repository timestamp Updated and deployed to update server." "https://update.joomla.org/cms"

trigger:
  branch:
    - main
  event:
    - cron
---
kind: signature
hmac: 4fccfa8faeef55bdf6c12bec1e9d5ee9eb36a7910208f363dcb691dca3ec565f
...
