kind: pipeline
name: default

steps:
- name: timestamp
  image: joomlaprojects/docker-images:tuf
  environment:
    GIT_USER_NAME: Joomla Drone
    GIT_USER_EMAIL: ci@joomla.org    
  commands:
    - mkdir -p /go/updates/keys || echo $?
    - echo ${KEY_TIMESTAMP}
    - echo ${GIT_USER_NAME} > /go/updates/keys/timestamp.json
    - ls -l /go/updates/keys
    - /go/docker-entrypoint.sh update-timestamp
  trigger:
    event:
    - cron
    - custom
