---
kind: pipeline
name: default
clone:
steps:
  - name: timestamp
    image: joomlaprojects/docker-images:tuf
    environment:
      ACCESS_TOKEN:
        from_secret: ACCESS_TOKEN
      KEY_TIMESTAMP:
        from_secret: KEY_TIMESTAMP
      GIT_USER_NAME: Joomla Drone
      GIT_USER_EMAIL: ci@joomla.org    
      GIT_BRANCH_NAME: ${DRONE_BRANCH}
    commands:
      - find .
      - mkdir -p /go/keys || true
      - echo $$KEY_TIMESTAMP > /go/keys/timestamp.json
      - ls -l /go/keys || true
      - /tuf/docker-entrypoint.sh update-timestamp || true
      - find .
    trigger:
      event:
      - cron
      - custom
---
kind: signature
hmac: a6f3f2ed21261b612d052724e5f43a5dd55168f98cbaa48eeaa358816bb255df
...